import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// Import global styles (side-effect); TypeScript may need declaration for CSS imports
// @ts-ignore: missing type declarations for CSS imports
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
